---
name: ci_lint_mutation
description: Used to hide the CiLint GraphQL mutation until we finish updating its structure
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/540764
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/191207
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/545316
milestone: '18.1'
group: group::pipeline authoring
type: wip
default_enabled: false
