---
name: work_item_status_transitions
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/498394
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/187686
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/540788
milestone: '18.1'
group: group::project management
type: wip
default_enabled: false
