---
api_type:
attr: anthropic_api_key
clusterwide: false
column: encrypted_anthropic_api_key
db_type: bytea
default:
description: This column is currently ignored.
encrypted: true
gitlab_com_different_than_default: false
jihu: false
not_null: false
