---
api_type:
attr: cloud_connector_keys
clusterwide: true
column: cloud_connector_keys
db_type: jsonb
default:
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: false
