---
api_type:
attr: enable_member_promotion_management
clusterwide:
column: enable_member_promotion_management
db_type: boolean
default: 'false'
description:
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
