---
api_type:
attr: feishu_app_key
clusterwide:
column: encrypted_feishu_app_key
db_type: bytea
default:
description:
encrypted: true
gitlab_com_different_than_default: false
jihu: false
not_null: false
