---
api_type:
attr: group_settings
clusterwide: false
column: group_settings
db_type: jsonb
default: "'{}'::jsonb"
description: "A jsonb column that stores a hash of related group_settings on the application_settings table"
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
