---
api_type:
attr: identity_verification_settings
clusterwide: true
column: identity_verification_settings
db_type: jsonb
default: "'{}'::jsonb"
description: 'Configuration settings related to identity verification'
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
