---
api_type:
attr: lets_encrypt_notification_email
clusterwide:
column: lets_encrypt_notification_email
db_type: character
default:
description:
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: false
