---
api_type:
attr: lets_encrypt_private_key
clusterwide:
column: encrypted_lets_encrypt_private_key
db_type: text
default:
description:
encrypted: true
gitlab_com_different_than_default: true
jihu: false
not_null: false
