---
api_type:
attr: lock_toggle_security_policy_custom_ci
clusterwide: false
column: lock_toggle_security_policy_custom_ci
db_type: boolean
default: 'false'
description: This column is currently ignored.
encrypted: false
gitlab_com_different_than_default: false
jihu: false
not_null: true
