---
api_type:
attr: package_registry
clusterwide:
column: package_registry
db_type: jsonb
default: "'{}'::jsonb"
description:
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
