---
api_type:
attr: pre_receive_secret_detection_enabled
clusterwide:
column: pre_receive_secret_detection_enabled
db_type: boolean
default: 'false'
description:
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
