---
api_type:
attr: runners_registration_token
clusterwide:
column: runners_registration_token
db_type: character
default:
description:
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: false
