---
api_type:
attr: service_ping_settings
clusterwide:
column: service_ping_settings
db_type: jsonb
default: "'{}'::jsonb"
description:
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: true
