---
api_type:
attr: static_objects_external_storage_auth_token_encrypted
clusterwide:
column: static_objects_external_storage_auth_token_encrypted
db_type: text
default:
description:
encrypted: false
gitlab_com_different_than_default: true
jihu: false
not_null: false
