---
api_type:
attr: telesign_api_key
clusterwide:
column: encrypted_telesign_api_key
db_type: bytea
default:
description:
encrypted: true
gitlab_com_different_than_default: true
jihu: false
not_null: false
