---
name: allow_runner_job_acknowledgement
description: Allow GitLab Runner to acknowledge acceptance of a CI job
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/464048
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/204265
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/568905
milestone: '18.5'
group: group::runner
type: gitlab_com_derisk
default_enabled: false
