---
name: allow_issuer_claim_customization_for_ci_id_tokens
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/391928
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/188632
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/544845
milestone: '18.1'
group: group::pipeline security
type: gitlab_com_derisk
default_enabled: false
