---
name: ci_new_downstream_errors_location
description: >
  Controls whether we read/write downstream error messages to `ci_job_messages` (new location) or
  to `ci_builds_metadata.config_options` (current location).
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/562953
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/202194
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/563006
milestone: '18.4'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
