---
name: ci_redis_enqueue_immediately
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/549077
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/194746
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/550225
milestone: '18.2'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
