---
name: ci_use_new_job_update_timeout_state
description: >
  When a job status transitions from :running to :pending, we call update_state_timeout.
  With this feature enabled, it calls update_state_timeout on the job rather than on
  ci_builds_metadata. It also sets the timeout values in ci_builds.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/552057
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/202970
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/566611
milestone: '18.4'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
