---
name: containing_commits_limit
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/366829
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/194863
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/550252
milestone: '18.2'
group: group::source code
type: gitlab_com_derisk
default_enabled: false
