---
name: delete_otp_no_webauthn
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/393419
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/166674
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/494388
milestone: '17.5'
group: group::authentication
type: gitlab_com_derisk
default_enabled: false
