---
name: duo_code_review_system_note
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/536723
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/189025
rollout_issue_url:
milestone: '18.0'
group: group::code review
type: gitlab_com_derisk
default_enabled: false
