---
name: filter_deleted_groups
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/455871
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/158309
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/470628
milestone: '17.2'
group: group::tenant scale
type: gitlab_com_derisk
default_enabled: false
