---
name: generate_ref_commits
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/436943
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/195831
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/558276
milestone: '18.3'
group: group::pipeline execution
type: gitlab_com_derisk
default_enabled: false
