---
name: go_get_handle_401_error
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/493732
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/167640
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/496539
milestone: '17.5'
group: group::source code
type: gitlab_com_derisk
default_enabled: false
