---
name: include_reserved_refs_in_pipeline_refs_filter
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/527279
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/186590
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/532291
milestone: '17.11'
group: group::runner
type: gitlab_com_derisk
default_enabled: false
