---
name: new_milestone_filtering_logic
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/429728
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/187632
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/536932
milestone: '18.0'
group: group::product planning
type: gitlab_com_derisk
default_enabled: false
