---
name: notification_event_store_migration_draft_published
description:
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/190667
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/541124
milestone: '18.0'
group: group::personal productivity
type: gitlab_com_derisk
default_enabled: false
