---
name: optimize_issues_banned_users_query
description: Optimize banned user clause for issue list queries
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/394980
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/189141
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/537923
milestone: '18.0'
group: group::project management
type: gitlab_com_derisk
default_enabled: false
