---
name: optimize_container_repository_has_tags
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/548145
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/198376
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/556772
milestone: '18.3'
group: group::container registry
type: gitlab_com_derisk
default_enabled: false
