---
name: optimized_snippet_search_query
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/525656
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/201906
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/562346
milestone: '18.4'
group: group::source code
type: gitlab_com_derisk
default_enabled: false
