---
name: packages_refactor_versions
description: Refactor Packages::Package#versions to use a package class instead of package_type.
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/548761
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/202042
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/562595
milestone: '18.4'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
