---
name: packages_create_package_service_refactor
description: Refactor create package service
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/548761
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/201306
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/561241
milestone: '18.4'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
