---
name: packages_terraform_module_presenter
description: Introduce terraform module presenter
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/552329
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/196116
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/552336
milestone: '18.3'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
