---
name: packages_refactor_packages_finder
description: Refactor packages finder
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/548761
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/202400
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/563421
milestone: '18.4'
group: group::package registry
type: gitlab_com_derisk
default_enabled: false
