---
name: populate_organization_id_in_runner_tables
description: Enable app code to populate new organization_id column in runner tables
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/523694
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/193202
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/547421
milestone: '18.1'
group: group::runner
type: gitlab_com_derisk
default_enabled: false
