---
name: preload_mr_diff_gitaly_data
description: Preload mr diff gitaly data before db txn
feature_issue_url:  https://gitlab.com/gitlab-org/gitlab/-/issues/527205
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/199466
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/558037
milestone: '18.3'
group: group::code review
type: gitlab_com_derisk
default_enabled: false
