---
name: render_label_notes_lazily
description: Skip usage of `resource_label_events.reference_html` so we can drop the column
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/521854
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/188576
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/536554
milestone: '18.0'
group: group::project management
type: gitlab_com_derisk
default_enabled: false
