---
name: use_merge_base_for_all_report_comparisons
description:
feature_issue_url:
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/192288
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/549351
milestone: '18.1'
group: group::security insights
type: gitlab_com_derisk
default_enabled: false
