---
name: use_cte_optimization_for_confidentiality_filter
description: Use a CTE to optimize confidentiality checks on Epic WorkItems List
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/548094
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/193857
rollout_issue_url:
milestone: '18.1'
group: group::product planning
type: gitlab_com_derisk
default_enabled: false
