description: "Reply comment on design annotations"
category: default
action: click_button
extra_properties:
identifiers:
product_group: ""
milestone:
introduced_by_url:
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
