description: "Change discussion sort direction"
category: default
action: change_discussion_sort_direction
label_description: ""
value_description: ""
extra_properties:
identifiers:
product_group: product_planning
milestone: "12.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/28717
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
additional_properties:
  property:
    description: "`[asc | desc]`"
