description: "Execute bubble menu control"
category: default
action: execute_bubble_menu_control
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_group: ide
milestone: "14.2"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/67363
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
additional_properties:
  label:
    description: "`content_editor`"
