description: "Select comment type from dropdown"
category: default
action: click_button
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_group: product_planning
milestone: "13.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/50933
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
additional_properties:
  label:
    description: "`[comment_button_title]_button`"
