description: "Click toggle external button on diff"
category: default
action: click_toggle_external_button
value_description: ""
extra_properties:
identifiers:
product_group: ""
milestone:
introduced_by_url:
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
additional_properties:
  label:
    description: "`diff_toggle_external_button`"
  property:
    description: "`diff_toggle_external`"
