description: "Click quickstart dropdown"
category: default
action: click_dropdown
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_group: group::package
milestone: "12.10"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/27990
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
additional_properties:
  label:
    description: "`quickstart_dropdown`"
