description: "Submit Docker form"
category: default
action: submit_form
property_description: ""
value_description: ""
extra_properties:
identifiers:
product_group: group::package
milestone: "12.8"
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/23844
distributions:
- ce
- ee
tiers:
- free
- premium
- ultimate
additional_properties:
  label:
    description: "`docker_container_retention_and_expiration_policies`"
