---
key_path: redis_hll_counters.ci_templates.p_ci_templates_jobs_dependency_scanning_monthly
description: Count of distinct projects that included the Jobs/Dependency-Scanning.gitlab-ci.yml template in a pipeline
product_group: composition_analysis
value_type: number
status: active
milestone: '14.8'
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/79454
time_frame: 28d
data_source: redis_hll
data_category: optional
instrumentation_class: RedisHLLMetric
tiers:
- free
- premium
- ultimate
options:
  events:
  - p_ci_templates_jobs_dependency_scanning
